nodes:
  - label: Literature
    # core["eid"]
    name: # core["dc:title"]
    properties:
      - date: # item["bibrecord"]["head"]["source"]["publicationdate"]
          - day:
          - month:
          - year:
      - xml: # core["prism:url"]
      - website:
      - open_access: # core["openaccess"]
      - page: #core["pageRange"] # perform subtraction here
      - correspondence: Author

  - label: Source # item["bibrecord"]["head"]["source"]
    # item["bibrecord"]["head"]["source"]["@srcid"]
    name:
      - properties:
          - website: # core["prism:url"]

  - label: Abstract
    content:

  - label: FundingAgency
    name:

  - label: Author # ab_data["authors"]
    name:
      - first_name:
      - surname:

  - label: Organization
    name:

  - label: Country
    name:

  - label: City
    name:

  - label: Keyword
    name:

  - label: Publisher
    name:

  - label: Classification # item["bibrecord"]["head"]["enhancement"]
    name:
    properties:
      - classification_type:

  - label: SubjectArea # ab_data["subject-areas"]
    name:

  # - label: Department
  #   name:

  # DO CHECK FOR SCOPUS IDENTIFIER !!
  # check ab_data["idxterms"]
