relationships:
  - type: FUNDED
    start_node: FundingAgency
    end_node: Literature # item["xocs:meta"]["xocs:funding-list"]["xocs:funding"]->["funding-agency-matched-string"]

  - type: AUTHORED
    start_node: Author
    end_node: Literature

  - type: AFFILIATED_WITH 
    start_node: Author or Literature  
    # item["bibrecord"]["head"]["author-group"]->["affiliation"]
    # aff 
    end_node: Department or Organization

  - type: CITY_OF
    start_node: City
    end_node: Country

  - type: OF
    start_node: Department
    end_node: Organization

  - type: LOCATED_AT
    start_node: Organization
    end_node: City

  - type: HAS_ABSTRACT # item["bibrecord"]["head"]["abstracts"] or core["dc:description"]
    start_node: Literature
    end_node: Abstract

  - type: IS_KEYWORD_OF # ab_data["authkeywords"]
    start_node: Keyword 
    end_node: Literature

  - type: PUBLISHED # item["bibrecord"]["head"]["source"]
    start_node: Publisher
    end_node: Literature

  - type: REFERENCED # item["bibrecord"]["tail"]["bibliography"]["reference"][1]["ref-info"]["refd-itemidlist"]["itemid"][1]["$"]
    start_node: Literature
    end_node: Literature
  
  - type: CITED # in core SCRAPE SCRAPE SCRAPE
    start_node: Literature
    end_node: Literature

  - type: IS_CLASSED
    start_node: Literature
    end_node: Classification

  - type: FROM
    start_node: Literature
    end_node: Source
      - properties: 
          - volume:
          - issue:
